customer_management/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path("", views.index, name="index"),

    path("<int:customer_id>/", views.detail, name="detail"),


]

gov_chat_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("customers/", include("customer_management.urls")),
]

customer_management/models.py
from django.db import models
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
import uuid
default_template_prompt = (
        "Use the following pieces of context to answer the question at the end. "
        "If you don't know the answer, just say that you don't know, don't try to make up an answer. "
        "Use three sentences maximum and keep the answer as concise as possible. "
        "Always say \"thanks for asking!\" at the end of the answer.\n"
        "{context}\n"
        "Question: {question}\n"
        "Helpful Answer:"
    )
class Customer(models.Model):
    def __repr__(self) -> str:
        return self.name
    def __str__(self) -> str:
        return self.name
    name = models.CharField(max_length=200)


class VectorStoreCollection(models.Model):
    def __str__(self) -> str:
        return self.name
    
    name = models.CharField(max_length=100)

class Website(models.Model):
     def __str__(self) -> str:
         return self.base_site
     customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
     base_site = models.CharField(max_length=200,unique=True)
     site_map = models.CharField(max_length=200,null=True,default=None, blank=True )
     update_site_map = models.BooleanField(default=False, null=False, blank= False)
     create_site_map = models.BooleanField(default=False, null = False, blank=False)
     site_map_last_scanned = models.DateField(null= True, blank=True)
     site_last_indexed = models.DateField(null=True, blank=True)
     site_doc_staging = models.CharField(max_length=200,null=True,default=None, blank=True )
     target_collections =  models.ManyToManyField(VectorStoreCollection)
     def __repr__(self) -> str:
         return f"{self.customer.name}-{self.base_site}"
class SupportedModels(models.TextChoices):
    GPT4All_J_v1_3_groovy = "GPT4All-J v1.3-groovy"


class ChatbotConfig(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    model = models.CharField(max_length=100,choices=SupportedModels.choices,default=SupportedModels.GPT4All_J_v1_3_groovy)
    temperature = models.FloatField(
        validators=[MinValueValidator(0.0), MaxValueValidator(1.0)],default=0
    )
    limit_time_seconds = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(3600)], default=60)
    limit_messages_per_time_per_device = models.IntegerField(validators=[MinValueValidator(0)],default=20)
    not_found_response = models.TextField(max_length=255,default="I'm sorry, I can't find information about your question")
    prompt_template = models.TextField(max_length=500, default=default_template_prompt, null= False, blank=False)
    default_collection = models.ForeignKey(VectorStoreCollection, blank= True, null=True, on_delete=models.SET_NULL)
    verbose = models.BooleanField(default=False, blank=False, null=False)
    return_source_documents = models.BooleanField(default=True, blank=False, null=False)
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

customer_management/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
# Create your views here.
from django.template import loader


from .models import Customer

def index(request):
    latest_customers = Customer.objects.order_by("name")[:5]
    context = {
        "customer_list": latest_customers,
    }
    return render( request, "customer/index.html", context)


def detail(request, customer_id):
    customer = get_object_or_404(Customer,pk=customer_id)
    return render(request,"customer/detail.html",{"customer":customer})

customer_management/templates/customer/detail.html
<h1>{{customer.name}}</h1>

<h2>Websites</h2>
{% for website in customer.website_set.all %}
    <h3>{{website.base_site}}</h3>
    
    <p>
        Doc Staging Location: {{website.site_doc_staging}}
    </p>

    <p>
        Collection Name: {{website.site_collection_name}}
    </p>
    <p>
        Sitemap Last Scanned: {{website.site_map_last_scanned}}
    </p>
    <p>
        Site Last Indexed: {{website.site_last_indexed}}
    </p>
    <div class="chatbot-settings-container">
        <input id="site-field" type="text" placeholder={{website.site_collection_name}}>
        <input id="customer-field" type="text" placeholder={{customer.name}}>
        <input id="chatbot-field" type="text" placeholder="chatbot_id">
      </div>
      <div class="chatbot-container">
          <div id="header">
              <h1>Chatbot</h1>
          </div>
          <div id="chatbot">
              <div id="conversation">
                <div class="chatbot-message">
                  <p class="chatbot-text">Hi! 👋 it's great to see you!</p>
                </div>
              </div>
              <form id="input-form">
                <message-container>
                  <input id="input-field" type="text" placeholder="Type your message here">
                  <button id="submit-button" type="submit">
                    <img class="send-icon" src="send-message.png" alt="">
                  </button>
                </message-container>
                  
              </form>
          </div>  
    
      </div>
      <script src="govchat.js"></script>
      <script src="test-project.js"></script>
{% endfor %}

<a href="/customers">back</a>

customer_management/templates/customer/index.html
{% if customer_list %}
    <ul>
    {% for customer in customer_list %}
        <li><a href="/customers/{{ customer.id }}/">{{ customer.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Customers are available.</p>
{% endif %}

{% load static %}
<img src="{% static 'customer/R.png' %}" alt="My image">